#!/bin/sh
set -e
changed_php="$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$' || true)"
[ -z "$changed_php" ] && exit 0
composer pint -- "$changed_php"
# re-stage formatted files
git add $changed_php
