#!/bin/sh
set -e
changed_php="$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$' || true)"
[ -z "$changed_php" ] && exit 0
echo "$changed_php" | xargs composer pint --
# re-stage formatted files
echo "$changed_php" | xargs git add
