SELECT
  ?album
  (SAMPLE(?albumLabel) AS ?albumLabel)
  (SAMPLE(?albumDescription) AS ?albumDescription)

  # Multi-valued performers
  (GROUP_CONCAT(DISTINCT STR(?performer); SEPARATOR="|") AS ?artists)

  (SAMPLE(?albumType) AS ?albumType)
  (SAMPLE(?publicationDate) AS ?publicationDate)
  (SAMPLE(?musicBrainzReleaseGroupId) AS ?musicBrainzReleaseGroupId)
  (SAMPLE(?wikipediaUrl) AS ?wikipediaUrl)
WHERE {
  VALUES ?performer { {{values}} }

  ?album wdt:P175 ?performer ;
        wdt:P31  ?albumType .

  VALUES ?albumType {
    wd:Q482994    # studio album
    wd:Q169930    # EP
    wd:Q134556    # single
    wd:Q222910    # compilation album
    wd:Q209939    # live album
    wd:Q59481898  # remix album
    wd:Q24672043  # soundtrack album
  }

  OPTIONAL { ?album wdt:P577 ?publicationDate . }
  OPTIONAL { ?album wdt:P436 ?musicBrainzReleaseGroupId . }

  OPTIONAL {
    ?wikipediaUrl schema:about ?album ;
                  schema:isPartOf <https://en.wikipedia.org/> .
  }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
GROUP BY ?album
ORDER BY ?album
