SELECT DISTINCT
  ?album
  ?albumLabel
  ?albumDescription
  ?artist
  ?albumType
  ?publicationDate
  ?musicBrainzReleaseGroupId
  ?wikipediaUrl
WHERE {
  VALUES ?artist { {{values}} }

  ?album wdt:P175 ?artist .
  ?album wdt:P31 ?albumType .

  # Filter to relevant album types
  VALUES ?albumType {
    wd:Q482994    # studio album
    wd:Q169930    # EP (extended play)
    wd:Q134556    # single
    wd:Q222910    # compilation album
    wd:Q209939    # live album
    wd:Q59481898  # remix album
    wd:Q24672043  # soundtrack album
  }

  OPTIONAL { ?album wdt:P577 ?publicationDate . }
  OPTIONAL { ?album wdt:P436 ?musicBrainzReleaseGroupId . }

  OPTIONAL {
    ?wikipediaUrl schema:about ?album ;
                  schema:isPartOf <https://en.wikipedia.org/> .
  }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
