# Artist social/streaming links - simple query for external IDs only
# Split from artist_enrich.sparql to reduce query complexity

SELECT
  ?artist
  ?twitter
  ?instagram
  ?facebook
  ?youtubeChannel
  ?spotifyArtistId
  ?appleMusicArtistId
  ?discogsArtistId
  ?deezerArtistId
  ?soundcloudId
  ?bandcampId
  ?subreddit
WHERE {
  VALUES ?artist { {{values}} }

  OPTIONAL { ?artist wdt:P2002 ?twitter . }
  OPTIONAL { ?artist wdt:P2003 ?instagram . }
  OPTIONAL { ?artist wdt:P2013 ?facebook . }
  OPTIONAL { ?artist wdt:P2397 ?youtubeChannel . }
  OPTIONAL { ?artist wdt:P1902 ?spotifyArtistId . }
  OPTIONAL { ?artist wdt:P2850 ?appleMusicArtistId . }
  OPTIONAL { ?artist wdt:P1953 ?discogsArtistId . }
  OPTIONAL { ?artist wdt:P2722 ?deezerArtistId . }
  OPTIONAL { ?artist wdt:P3040 ?soundcloudId . }
  OPTIONAL { ?artist wdt:P3283 ?bandcampId . }
  OPTIONAL { ?artist wdt:P3984 ?subreddit . }
}
