SELECT DISTINCT ?artist WHERE {
  {
    # Solo artists: humans with occupation musician
        ?artist wdt:P31 wd:Q5 ;
        wdt:P434 ?mbid .   # MusicBrainz artist ID
  }
  UNION
  {
    # Bands / groups
    ?artist wdt:P31/wdt:P279* wd:Q215380 .
  }
}
ORDER BY ?artist
LIMIT {{limit}}
OFFSET {{offset}}